# Generated by Django 4.2.21 on 2025-05-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_location_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='table_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.table'),
            preserve_default=False,
        ),
    ]
