# Generated by Django 4.2.21 on 2025-05-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
